### ISSUE TITLE
[Bug] Setting TabView.SelectedIndex does not "visually" switch tabs

### ISSUE THREAD

**Issue by kazo0** [xamarin/XamarinCommunityToolkit#595]
### Description
If I programmatically set the `SelectedIndex` of a `TabView` to say 1 when it is originally on `SelectedIndex` of 0, it appears that internally the new Tab is selected but visually the the `TabView` appears to still be on Tab 0. If you were then to physically tap on Tab 1, nothing would happen since it is internally already on Tab 1. Tapping on Tab 0 and then Tab 1 will finally successfully show Tab 1. See gif below:

### Steps to Reproduce

XAML:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
			 xmlns:xct="http://xamarin.com/schemas/2020/toolkit"
             x:Class="App4.MainPage">

	<StackLayout>
		<Button Text="Change Tab"
                              Clicked="Button_Clicked" />
		<xct:TabView x:Name="MyTabView"
					 TabIndicatorPlacement="Bottom"
					 TabIndicatorColor="Orange">
			<xct:TabViewItem Text="First">
				<Label Text="First Tab" />
			</xct:TabViewItem>
			<xct:TabViewItem Text="Second">
				<Label Text="Second Tab" />
			</xct:TabViewItem>
		</xct:TabView>
	</StackLayout>
</ContentPage>
```

Code Behind:
```csharp
namespace App4
{
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
		}

		private void Button_Clicked(object sender, EventArgs e)
		{
			MyTabView.SelectedIndex = 1;
		}
	}
}
```

### Expected Behavior
Upon button click, the `TabView` should visually navigate to the next Tab on `SelectedIndex` change.
### Actual Behavior
![tabview](https://user-images.githubusercontent.com/4793020/99815608-84135100-2b18-11eb-956d-560f2c1e0e9c.gif)

### Basic Information

- Version with issue: 1.0.0-pre5
- IDE:
- Platform Target Frameworks: 
  - iOS:  14.2
  - Android: 10.0

### Workaround
```csharp
MethodInfo dynMethod = MyTabView.GetType().GetMethod("UpdateSelectedIndex", BindingFlags.NonPublic | BindingFlags.Instance);
dynMethod?.Invoke(MyTabView, new object[] { 1, false });
```

**Comment by kazo0** [comment]
Issue seems to be because by the time `UpdateSelectedIndex` is called, the `SelectedIndex` has already been changed so the method returns early because of:
```csharp
if (oldPosition == newPosition)
	return;
```

Ugly workaround would be to use reflection instead of setting `SelectedIndex` directly:

```csharp
MethodInfo dynMethod = MyTabView.GetType().GetMethod("UpdateSelectedIndex", BindingFlags.NonPublic | BindingFlags.Instance);
dynMethod?.Invoke(MyTabView, new object[] { 1, false });
```

**Comment by jfversluis** [comment]
Thanks for the report @kazo0 ! Would you maybe be willing and able to try pre6? I think changes are small, but who knows! Maybe we fixed it :D 

If not, did you try on all platforms? I'm guessing this is in shared code so it will affect all platforms. Thanks!

**Comment by kazo0** [comment]
Hi @jfversluis! Confirmed that it is still happening in pre6

**Comment by gresolio** [comment]
I can also confirm that it is still happening in v1.0.0-pre6.

**Comment by jfversluis** [comment]
Alrighty, sorry about that! But thanks for letting us know and verifying!

**Comment by jfversluis** [comment]
I think this is solved by #903

**Comment by gresolio** [comment]
I think this is not solved by #903 yet (BindingMode.TwoWay fixes #870).

This issue is related to [Bug] TabView - Tab is not being selected #630.
Just a little bit different test case scenario, but the same reason.

**Comment by jfversluis** [comment]
Hmm maybe I was too quick on this 😬

**Comment by xiedongweo** [comment]
> Issue seems to be because by the time `UpdateSelectedIndex` is called, the `SelectedIndex` has already been changed so the method returns early because of:
> 
> ```cs
> if (oldPosition == newPosition)
> 	return;
> ```
> 
> Ugly workaround would be to use reflection instead of setting `SelectedIndex` directly:
> 
> ```cs
> MethodInfo dynMethod = MyTabView.GetType().GetMethod("UpdateSelectedIndex", BindingFlags.NonPublic | BindingFlags.Instance);
> dynMethod?.Invoke(MyTabView, new object[] { 1, false });
> ```

I tried this workaround in my project, but it still did not work.

**Comment by udde** [comment]
This still does not work on iOS! 

Any ideas?

**Comment by sp-sabik** [comment]
@udde As far as I know, this bug is already fixed. Try to update Xamarin.CommunityToolkit nuget package, maybe you are using some old TabView version. Alternatively, you can check [TabViewIndexWorkaround](https://github.com/xamarin/XamarinCommunityToolkit/issues/630#issuecomment-778601734) (works for old versions with a bug).

**Comment by udde** [comment]
Hi, thanks for the response!

I am using the latest version. It is not fixed there. 

I am using the workaround presented.
And i just realized this...

My issue was that i wanted the view to start on another tab index. So i put Selected index = 1; After InitializeComponent(); was called in the constrctor.
Doing so, the Tabview_SelectionChanged was actually called twice (only on iOS), and i think that messed up the workaround execution.

My solution is now to set the tab index only on the Android platform, in the constructor. And I handle the first event on iOS explicitly, in the event handler.

**Comment by DanielGlick45** [comment]
@udde Can you explain your workaround here? I am running into the same issue that you were but I didn't understand how I should implement it

**Comment by kazo0** [comment]
@DanielGlick45 you would basically replace any line that is setting the SelectedIndex of the TabView with the workaround code.

You can take a look how I'm using it here: https://github.com/kazo0/MVVM-Samples/blob/fc5c4dcbec4cfe3b9b6511ffa30d7f0070c87c86/samples/MvvmSampleXF/MvvmSampleXF/Views/RedditBrowserPage.xaml.cs#L37

**Comment by DanielGlick45** [comment]
@kazo0 I understand that workaround. I was asking @udde for him to explain his workaround, where iOS was firing SelectionChanged multiple times if SelectedIndex was set in the constructor

**Comment by kazo0** [comment]
@DanielGlick45 oh woops my bad! I totally thought you had tagged me in that question

**Comment by udde** [comment]
@DanielGlick45 Hi, sorry I forgot to get back to you on this, I saw your mention last week but was not at the office at that moment.

In the page constructor I simply do this:
```
if (Device.RuntimePlatform == Device.Android)
{
    tabview.SelectedIndex = SomeCondition ? 0 : 1;
}
```
Then, in the SelectionChanged event I do this:
```
private void Tabview_SelectionChanged(object sender, Xamarin.CommunityToolkit.UI.Views.TabSelectionChangedEventArgs e)
{
    if (e.OldPosition == -1)
    {
        Device.BeginInvokeOnMainThread(() =>
        {
            var index = SomeCondition ? 0 : 1;
            System.Reflection.MethodInfo dynMethod = tabview.GetType()
                .GetMethod("UpdateSelectedIndex", System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
            dynMethod?.Invoke(tabview, new object[] { index, false });
        });
    }
}
```

Hope that helps!

**Comment by AndriDev** [comment]
Is it ok that in 2023 we still should use ugly workaround in IOS ?
Or maybe this is already fixed in MAUI?
