### ISSUE TITLE
Samples build

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/XamarinCommunityToolkit#610]
1. Right now Samples project is not built on CI
2. Sample project is broken after folder structure changes. (Before: XamarinCommunityToolkit, After: Xamarin.CommunityToolkit)

**Comment by pictos** [comment]
This one is fixed by #612, @VladislavAntonyuk can you confirm that?

**Comment by VladislavAntonyuk** [comment]
@pictos it is partially fixed:
Platform Project files are still broken
```
<ProjectReference Include="..\XamarinCommunityToolkitSample\Xamarin.CommunityToolkit.Sample.csproj">
			<Project>{81aade72-d666-4ab0-83d9-8fe366e0755e}</Project>
			<Name>Xamarin.CommunityToolkit.Sample</Name>
		</ProjectReference>
		<ProjectReference Include="..\XamarinCommunityToolkit\Xamarin.CommunityToolkit.csproj">
			<Project>{b0dcdf81-953d-47da-a7d4-0565339bf07c}</Project>
			<Name>Xamarin.CommunityToolkit</Name>
		</ProjectReference>
```

**Comment by VladislavAntonyuk** [comment]
I will create a PR today

**Comment by AndreiMisiukevich** [comment]
Confirmed

Here is what we need to do
![Uploading image.png…]()

**Comment by AndreiMisiukevich** [comment]
Oh, and Xamarin.CommunityToolkit as well for sure
