### ISSUE TITLE
Xamarin Forms: MediaElement: Feature Request: Stick the control bar always on top of the screen

### ISSUE THREAD

**Issue by sreejithsree139** [xamarin/XamarinCommunityToolkit#669]
I am using `MediaElement` for playing audio. My problem is the controls(Play, pause, and duration bar) are not showing always. If I tap on the `MediaElement` the controls are showing else only a black screen. I need to keep the controls always there at the whole time of audio play.

**Currently audios are playing like below:**

[![enter image description here][1]][1]

I tried true value for `KeepScreenOn` and `ShowsPlaybackControls` properties, but no luck.

**I need output like below screenshot:**

[![enter image description here][2]][2]

I can't use webview here because I need to perform some operations when the audio play end.

  [1]: https://i.stack.imgur.com/IV52a.jpg
  [2]: https://i.stack.imgur.com/s667v.jpg

**Comment by jfversluis** [comment]
I think this issue was fixed. @sreejithsree139 could you please install the latest pre-release of the Xamarin.CommunityToolkit and verify this works for you?

**Comment by AndreiMisiukevich** [comment]
@jfversluis not fixed yet

The request is keeping playback controls always visible, as I understand

**Comment by AndreiMisiukevich** [comment]
https://stackoverflow.com/questions/4458529/mediacontroller-always-show-on-android

**Comment by AndreiMisiukevich** [comment]
Well, seems it's hard to achieve it on iOS

> That's not possible. There is not any Public API of AVPlayerViewController to keep playback controls visible all time. You must have to make your own custom playback controls for this i.e. play button, seekbar, duration label etc.

https://stackoverflow.com/questions/53944561/avplayerviewcontroller-how-to-display-always-playback-controls#:~:text=There%20is%20not%20any%20Public,%2C%20seekbar%2C%20duration%20label%20etc.


@jfversluis are we going to implement it then?

**Comment by AndreiMisiukevich** [comment]
It seems the "always visible" control bar supposed to be a custom-built solution.

Put media element inside absolute layout, then put custom controls above (buttons, slider etc.)

**Comment by sreejithsree139** [comment]
@jfversluis and @AndreiMisiukevich  I have installed the latest xamarin forms pre-release.

Getting below error for MediaElement:

	Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
	Error		 : XamlC error XFC0000 : Cannot resolve type "MediaElement"

[![enter image description here][1]][1]


  [1]: https://i.stack.imgur.com/FlU7E.png

**Comment by AndreiMisiukevich** [comment]
@sreejithsree139 MediaElement migrated to XamarinCommunityToolkit

**Comment by jfversluis** [comment]
I'm kind of confused what is all going on in this issue :D The title speaks of a feature request, but in the issue I see bugs.

Anyhow, as per your latest comment @sreejithsree139 you will need to import the Xamarin.CommunityToolkit namespace first and use that. For example:

```xaml
<ContentPage xmlns:toolkit="http://xamarin.com/schemas/2020/toolkit">
    <toolkit:MediaElement />
</ContentPage>
```

Also see the example page here: https://github.com/xamarin/XamarinCommunityToolkit/blob/main/samples/XCT.Sample/Pages/Views/MediaElementPage.xaml

**Comment by jfversluis** [comment]
For now I would say we're not going to implement this. The MediaElement works as expected on the native platforms and I think you have all the events, methods and properties to create your own playback controls, see the Docs [here](https://github.com/MicrosoftDocs/xamarin-communitytoolkit/blob/master/docs/views/mediaelement.md#implement-custom-transport-controls). It might be something nice to add in the future, but for now I think other things will have priority for the MediaElement.

Closing this issue as such, if you believe there is an actual bug or a feature request, please open an issue with the right template and provide as much detail as possible.

This might be something good to note though on the MediaElement Docs pages that "ShowPlaybackControls" is only temporary on iOS.
