### ISSUE TITLE
[Bug] [CameraView] [iOS] Taking photos doesn't work on iOS using Hot Restart

### ISSUE THREAD

**Issue by michaldivis** [xamarin/XamarinCommunityToolkit#901]
### Description
I'm using Hot Restart in Windows to debug my Xamarin.Forms app on iOS. Whenever I take a photo (trigger the `ShutterCommand`), the app UI freezes and the `MediaCaptured` event never gets called.

I also get this lovely exception:
```
=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1010ae8c4):0x1010ae8b4  a8 83 5e f8 09 00 80 52 09 01 00 39 a8 03 5f f8  ..^....R...9.._.
0x1010ae8c4  09 01 40 39 69 0f 00 34 a8 03 5f f8 09 01 c0 39  ..@9
.

=================================================================
	Managed Stacktrace:
=================================================================

.4.._....9
0x1010ae8d4  29 8d 00 71 e8 03 09 aa 08 7d 40 d3 1f 69 01 f1  )..q.....}@..i..
0x1010ae8e4  e8 13 00 f9 68 0b 00 54 08 00 00 90 08 61 2c 91  ....h..T.....a,
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x00020>
	  at UIKit.UIApplication:Main <0x00038>
	  at XctCameraApp01.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x0008c>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00254>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================
```

### Steps to Reproduce

1. CameraPage.xaml
```xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage
    x:Class="XctCameraApp01.MainPage"
    xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:xct="http://xamarin.com/schemas/2020/toolkit">

    <Grid>
        <xct:CameraView
            x:Name="cameraView"
            CaptureMode="Photo"
            OnAvailable="cameraView_OnAvailable">
            <xct:CameraView.Behaviors>
                <xct:EventToCommandBehavior Command="{Binding PhotoCapturedCommand}" EventName="MediaCaptured" />
            </xct:CameraView.Behaviors>
        </xct:CameraView>
        <Button
            Margin="20"
            Command="{Binding ShutterCommand, Source={x:Reference cameraView}}"
            HorizontalOptions="Center"
            IsEnabled="{Binding CanTakePhoto}"
            Text="Take photo"
            VerticalOptions="End" />
    </Grid>

</ContentPage>
```
2. CameraPage.xaml.cs
```csharp
using Xamarin.Forms;

namespace XctCameraApp01
{
    public partial class MainPage : ContentPage
    {
        private readonly MainViewModel _model;

        public MainPage()
        {
            InitializeComponent();
            BindingContext = _model = new MainViewModel();
        }

        private void cameraView_OnAvailable(object sender, bool e)
        {
            _model.CanTakePhoto = e;
        }
    }
}
```
3. MainViewModel.cs
```csharp
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Input;
using Xamarin.CommunityToolkit.ObjectModel;
using Xamarin.CommunityToolkit.UI.Views;
using Xamarin.Essentials;
using Xamarin.Forms;
using static Xamarin.Essentials.Permissions;

namespace XctCameraApp01
{
    public class MainViewModel : ObservableObject
    {
        private bool _canTakePhoto;
        public bool CanTakePhoto
        {
            get => _canTakePhoto;
            set => SetProperty(ref _canTakePhoto, value);
        }

        public ICommand PhotoCapturedCommand => new AsyncCommand<MediaCapturedEventArgs>(PhotoCapturedAsync);

        private async Task PhotoCapturedAsync(MediaCapturedEventArgs args)
        {
            await SavePhotoAsync(args.ImageData);
        }

        private async Task SavePhotoAsync(byte[] photoData)
        {
            var readStatus = await CheckAndRequestPermissionAsync(new StorageRead());
            if (readStatus != PermissionStatus.Granted)
            {
                // Notify user permission was denied
                return;
            }

            var writeStatus = await CheckAndRequestPermissionAsync(new StorageWrite());
            if (writeStatus != PermissionStatus.Granted)
            {
                // Notify user permission was denied
                return;
            }

            var savedPhotoPath = await SavePhotoFileAsync(photoData, Guid.NewGuid().ToString() + ".jpg");

            LastSavedPhotoPath = savedPhotoPath;
        }

        private async Task<string> SavePhotoFileAsync(byte[] photoData, string fileName)
        {
            var dirPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            Directory.CreateDirectory(dirPath);

            var savedPhotoPath = Path.Combine(dirPath, fileName);

            using (var fs = new FileStream(savedPhotoPath, FileMode.OpenOrCreate, FileAccess.ReadWrite, FileShare.None))
            {
                await fs.WriteAsync(photoData, 0, photoData.Length);
                return savedPhotoPath;
            }
        }

        public async Task<PermissionStatus> CheckAndRequestPermissionAsync<T>(T permission) where T : BasePermission
        {
            var status = await permission.CheckStatusAsync();
            if (status != PermissionStatus.Granted)
            {
                status = await permission.RequestAsync();
            }

            return status;
        }
    }
}
```

4. Launch app on an iOS device using Hot Restart and click the 'Take photo' button

### Expected Behavior
`CameraView` takes a photo and triggers the `MediaCaptured` event

### Actual Behavior
The `MediaCaptured` event doesn't get triggered, the camera preview keeps going.

### Basic Information

- Version with issue: 1.0.2
- Last known good version: ?
- IDE: VS 2019 Professional v16.8.5
- Platform Target Frameworks:
  - iOS:  Default (14.3 I guess)
  - Android: 10.0
  - UWP:  nope
- Android Support Library Version: Android X
- Nuget Packages: 
  - Xamarin.Forms 5.0.0.1931
  - Xamarin.Essentials 1.6.1
- Affected Devices:
  - iPad Air 2 (iOS 13.7)

### Reproduction repo
https://github.com/michaldivis/camera-view-app

**Comment by pictos** [comment]
@michaldivis can you test using the event handler? If you can attach a repro that would be great, thanks!

**Comment by UKDeveloper99** [comment]
I've found the shutter command to be pretty unreliable on iOS. It's one of the issues I've been meaning to raise. Sometimes it just fails without explanation and the media capture event handler never returns. Could be related to linking maybe I noticed it has a Linker attribute. @jfversluis  any ideas?

**Comment by pictos** [comment]
@UKDeveloper99 can you provide a repro? That way I can look into it.

**Comment by michaldivis** [comment]
@pictos I've also tried using the event handler (instead of the `EventToCommandBehavior`) with no success. I'll attach a repo later today. Thanks!

**Comment by michaldivis** [comment]
@pictos I've attached a reproduction repo. You can find it here: https://github.com/michaldivis/camera-view-app

**Comment by michaldivis** [comment]
I've inspected the iOS FormsCameraView class and I've found the problem. The thing is I don't know what's causing it.

When debugging, the `PhotoCaptureDelegate`'s `OnFinishCapture` callback never gets called.
It's on this [line](https://github.com/xamarin/XamarinCommunityToolkit/blob/12ee0d01d66adf2c97f96d977773832edec88002/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs#L209)

One other thing is that the null check on this [line](https://github.com/xamarin/XamarinCommunityToolkit/blob/12ee0d01d66adf2c97f96d977773832edec88002/src/CommunityToolkit/Xamarin.CommunityToolkit/Views/CameraView/iOS/FormsCameraView.ios.cs#L191) is checking the `videoOutput` instead of the `photoOutput`. I've already submitted a PR fixing that (PR #923).

**Comment by ssbssb-cmd** [comment]
Hi - I'm having the same issue when calling cameraView.Shutter() the MediaCapture event isn't being hit. I'm seeing this in Debug mode as well as Release mode.
MediaCaptureFailed also doesn't get hit

**Comment by eyalvayness** [comment]
Hi all,

I am also having the same issue.
Wether using the _ShutterCommand_ or the _Shutter_ method, both _MediaCaptured_ and _MediaCaptureFailed_ Events are not get called.

I tried disabling **Hot Restart** but the issue persists.

**Comment by amistry79** [comment]
@michaldivis  I see PR #923 has been merged however issue is not fixed. May I know which version or build should be used for this fixed? We are using v1.1.0

**Comment by monahk** [comment]
Any new update on this fix?

**Comment by samafshari** [comment]
I also have this problem. Calling Shutter, expecting MediaCaptured to be called, but it's not. Works fine on Android, doesn't work on iOS. Using v1.1.0

**Comment by DanKyungu** [comment]
Resolved in the 1.20 version.

**Comment by joehanna** [comment]
Still happening for me, even tried 1.3.0-pre1 and it still happening. Sometimes it works for one or two photos and then it stops working.

**Comment by ricardocesarcara** [comment]
Still happening for me. Sometimes it works for one or two photos and then it stops working. (1.2.0 version)

**Comment by MintDeville** [comment]
Is this an Error only happening with Hot restart and it will work if I compile it with an Apple mac?
I cant test this, since I dont have a Mac. Only an IPhone and Visual Studio on Windows

**Comment by joehanna** [comment]
This happens in production, App Store apps, not just in development. They get one or two photos and then it stops firing the event.

**Comment by ricardocesarcara** [comment]
For me too, it's happening in production. I still can't find a way to make it work.

**Comment by MintDeville** [comment]
I found this on stackoverflow

public class myDelegate : AVCapturePhotoCaptureDelegate {

    public override void DidFinishCapture(AVCapturePhotoOutput captureOutput, AVCaptureResolvedPhotoSettings resolvedSettings, NSError error)
    {
        base.DidFinishCapture(captureOutput, resolvedSettings, error);
    }

    public override void DidFinishProcessingPhoto(AVCapturePhotoOutput output, AVCapturePhoto photo, NSError error)
    {
        base.DidFinishProcessingPhoto(output, photo, error);

        if (error == null)
        {
            var photodata = photo.FileDataRepresentation;
        }
    }
}
https://stackoverflow.com/questions/64457742/how-to-get-captured-image-of-custom-renderer-camera-in-ios-xamarin-forms
I got a working control with it. Difference it seems it uses DidFinishProcessingPhoto instead DidFinishCapture

**Comment by NewHope1** [comment]
Sounds like unreliable tool to use. Maybe time to switch to another more reliable toolkit.

**Comment by jfversluis** [comment]
@NewHope1 if that is your assessment please feel free to do so :)

All the rest, I think this has been fixed in 1.3-pre2. Didn't you confirm this to be working @joehanna ?

**Comment by joehanna** [comment]
@jfversluis yes, 1.3-pre2 resolves the camera issue for me. I can’t speak of hot restart but regular production use is great now.

**Comment by jfversluis** [comment]
I'm going to assume this is fixed for now then. If that is not the case for Hot Restart @michaldivis please let me know!

**Comment by michaldivis** [comment]
@jfversluis I'll let you know if I find any problems, thanks!

**Comment by ShinichiHezemansCortegs** [comment]
I still have the problem with hot restart. 

I took the reproduction repo  https://github.com/michaldivis/camera-view-app, updated the nuget packages and the community toolkit to 1.3.0-pre2.

I don't know if my problem is the same, my app just crashes

`=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x104e60768):0x104e60758  a8 83 5e f8 09 00 80 52 09 01 00 39 a8 03 5f f8  ..^....R...9.._.
0x104e60768  09 01 40 39 69 0f 00 34 a8 03 5f f8 09 01 c0 39  ..@9i..4.._....9
0x104e60778  29 8d 00 71 e
8 03 09 aa 1f 69 01 f1 e8 13 00 f9  )..q.....i......
0x104e60788  88 0b 00 54 08 00 00 90 08 e1 26 91 eb 13 40 f9  ...T......&...@.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x00020>
	  at UIKit.UIApplication:Main <0x00038>
	  at CameraViewApp.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.iOS.HotRestart.Application:Run <0x001c8>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x0005a>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================`

**Comment by ShinichiHezemansCortegs** [comment]
@michaldivis It dit work with hot restart right?

**Comment by ShinichiHezemansCortegs** [comment]
Although I crash with hot restart in version 1.0.0 1.0.3 1.1.0 1.2.0 and 1.3.0-pre2

**Comment by michaldivis** [comment]
@ShinichiHezemansCortegs Yes, I am having the same problem. **It still doesn't work**. I get the exact same error when I run the app.

Upon tapping the "Take photo" button, the camera becomes busy, but nothing else happens, except for a crash report in the output.

I'm using my [reproduction app](https://github.com/michaldivis/camera-view-app) and I've updated the nuget packages.

### Nuget packages
- Xamarin.CommunityToolkit 1.3.0-pre2
- Xamarin.Forms 5.0.0.2083
- Xamarin.Essentials 1.7.0

### Other information
- Visual Studio Professional 2019 v16.10.4
- Using Hot Restart with an Apple iPad Air 2 (iOS 13.7)

### Full crash report
```
=================================================================
	Native Crash Reporting
=================================================================

Got a segv while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

=================================================================

=================================================================
	Native stacktrace:
=================================================================

	0x100778120 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_dump_native_crash_info

	0x10076ecbc - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_handle_native_crash

	0x10077ba60 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_sigsegv_signal_handler_debug

	0x199c53894 - /usr/lib/system/libsystem_platform.dylib : <redacted>

	0x10090aa14 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_collapse_struct_name

	0x1009161f0 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : _ZL15param_iter_next14IteratorActionPvPKcmS0_Pj

	0x10090ffb4 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_invoke_trampoline

	0x1009160cc - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_arch_trampoline

	0x1a423b298 - /System/Library/Frameworks/AVFoundation.framework/AVFoundation : <redacted>
	0x1a423b324 - /System/Library/Frameworks/AVFoundation.framework/AVFoundation : <redacted>

	0x100916c70 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_arm64_common_trampoline
	0x1a42c2b0c - /System/Library/Frameworks/AVFoundation.framework/AVFoundation : <redacted>

	0x199c0f9a8 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x199c10524 - /usr/lib/system/libdispatch.dylib : <redacted>
	0x199bc25b4 - /usr/lib/system/libdispatch.dylib : <redacted>

	0x199ec86bc - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>

	0x199ec3590 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : <redacted>

	0x199ec2ba8 - /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x1a4039344 - /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal

	0x19dffe3e4 - /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x1009248fc - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall

	0x100923010 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper

	0x100917eb0 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x10077ed3c - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke
	0x10082d2c0 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked

	0x100919a8c - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full

	0x100833974 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_try_invoke_array

	0x100923010 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall_wrapper

	0x1007db9c4 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_InternalInvoke
	0x1007ebb68 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : ves_icall_InternalInvoke_raw
	0x1009248fc - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : do_icall

	0x199d4a8f0 - /usr/lib/system/libdyld.dylib : <redacted>

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x10090a8f4):
	0x10072bc34 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : main

	0x10082d2c0 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_invoke_checked
	0x100832564 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_runtime_exec_main_checked
	0x1007638f4 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_exec
	0x100915984 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : xamarin_main

	0x100919a8c - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : interp_exec_method_full
	0x100917eb0 - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : interp_runtime_invoke
	0x10077ed3c - /private/var/containers/Bundle/Application/CE9350D9-6DB2-4529-AD2B-0BB97B6902BF/CameraViewApp.iOS.app/Xamarin.PreBuilt.iOS : mono_jit_runtime_invoke

0x10090a8e4  a8 
83 
5e f8 
00 80 52 09 01 
09 
00 
39 a8 03 5f f8  
..^....R...9.._.

0x10090a8f4  09 01 40 39 69 0f 00 34 a8 03 5f f8 09 01 c0 
01 f1  )..q.....}@..i..
0x10090a914  e8 13 00 f9 68 0b 00 54 08 00 00 90 08 21 2d 91  ....h..T.....!-.

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at UIKit.UIApplication:UIApplicationMain <0x000b8>
	  at UIKit.UIApplication:Main <0x00020>
	  at UIKit.UIApplication:Main <0x00038>
	  at CameraViewApp.iOS.Application:Main <0x00012>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
	  at <unknown> <0xffffffff>
	  at System.Reflection.RuntimeMethodInfo:InternalInvoke <0x00030>
	  at System.Reflection.RuntimeMethodInfo:Invoke <0x000fc>
	  at System.Reflection.MethodBase:Invoke <0x0001a>
	  at Xamarin.PreBuilt.iOS.Applications:Main <0x00254>
	  at <Module>:runtime_invoke_direct_void_string[] <0x00092>
=================================================================
```

**Comment by ShinichiHezemansCortegs** [comment]
When not using hot restart (using the mac) the app no longer crashes. But the MediaCaptured and MediaCaptureFailed still don't get called. 
The fix doesn't work for me.

### Nuget packages

- Xamarin.CommunityToolkit 1.3.0-pre2
- Xamarin.Essentials 1.7.0
- Xamarin.Forms 5.0.0.2083

### hardware

- IPad Air 4th generation

**Comment by ShinichiHezemansCortegs** [comment]
I get the same behavior when using version 1.2.0 1.1.0 1.0.3 and 1.0.0
In what version dit it work? The CameraView plays a core role in my application so I am looking for a working version.
Are there any alternatives to CameraView?

**Comment by michaldivis** [comment]
I didn't get it to work in any version, at least not when using Hot Restart.

I never tried it when connected to a Mac (my setup doesn't allow that), so I have no idea whether that works or not. And sadly, the iOS simulator doesn't support a camera, so that's not an option.

@ShinichiHezemansCortegs I'm not aware of any alternative to the `CameraView`. I've found many example implementations of a camera view renderer but none of them worked on all platforms, some didn't work at all.

**Comment by ShinichiHezemansCortegs** [comment]
@jfversluis can this issue be reopened since the hot restart was not fixed?

**Comment by ShinichiHezemansCortegs** [comment]
I made a mistake, I put the breakpoint on the methode and not the code block. That is why MediaCaptured and MediaCaptureFailed were not called. This was not using hot restart but with a mac. With hot restart the app still crashes as motioned before.
